/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 439593d369204ce2bd2698f5f4fe9de4)
declare namespace Cloudflare {
	interface Env {
		AQI_API: Fetcher /* aqi-backend */;
	}
}
interface Env extends Cloudflare.Env {}
